// src/lib/seed-data.ts
import type { Recommendation, Category, CostLevel, LocationType } from '../types'

export const SEED_RECOMMENDATIONS: Recommendation[] = [
  // ACTIVITIES
  { title: 'Sunset Photography Walk', category: 'activities', description: 'Grab your phone or camera and walk to a scenic spot to capture the golden hour. No skill needed — just look for interesting light, shadows, and colors.', why_good: 'Combines light exercise with creative expression. Free, meditative, and you end up with photos you actually want to keep.', best_for: 'Solo or with a friend, clear evenings, creative moods', mood_tags: ['relaxed', 'creative', 'bored'], interest_tags: ['photography', 'nature', 'walking', 'art'], time_needed: '1-2 hours', cost_level: 'free', location_type: 'outdoor', tags: ['photography', 'nature', 'walking', 'creative', 'free'] },
  { title: 'Try a New Recipe Challenge', category: 'activities', description: 'Pick a cuisine you have never cooked before, find a recipe, and make a full meal from scratch. Bonus points if you have to buy at least one ingredient you have never used.', why_good: 'Expands your cooking skills, gives you a sense of accomplishment, and you get to eat the results.', best_for: 'Solo or with a partner, rainy days, hungry and curious', mood_tags: ['creative', 'bored', 'cozy'], interest_tags: ['cooking', 'food', 'learning'], time_needed: '1-3 hours', cost_level: 'low', location_type: 'indoor', tags: ['cooking', 'food', 'creative', 'learning'] },
  { title: 'Neighborhood Exploration Walk', category: 'activities', description: 'Pick a direction you have never walked in your neighborhood and just go. No destination. Notice architecture, gardens, street art, and hidden spots.', why_good: 'Rediscover your own area. Free exercise. Often leads to finding new favorite spots.', best_for: 'Solo, curious moods, nice weather', mood_tags: ['adventurous', 'bored', 'relaxed'], interest_tags: ['walking', 'exploring', 'urban'], time_needed: '30 min - 1 hour', cost_level: 'free', location_type: 'outdoor', tags: ['walking', 'exploring', 'free', 'urban'] },
  { title: 'Learn a Card Magic Trick', category: 'activities', description: 'YouTube a simple card trick and practice until you can perform it smoothly. Then surprise someone with it.', why_good: 'Takes 20 minutes to learn, creates a moment of wonder, and is a great social icebreaker.', best_for: 'Solo practice, then showing friends or family', mood_tags: ['bored', 'social', 'creative'], interest_tags: ['magic', 'social', 'skills'], time_needed: '20-30 min', cost_level: 'free', location_type: 'any', tags: ['magic', 'social', 'skills', 'free'] },
  { title: 'DIY Spa Night', category: 'activities', description: 'Make a face mask from kitchen ingredients (honey + oatmeal works great), light a candle, put on ambient music, and give yourself a proper at-home spa treatment.', why_good: 'Relaxing, costs almost nothing, and actually makes you feel noticeably better after.', best_for: 'Solo, tired or stressed evenings', mood_tags: ['tired', 'cozy', 'relaxed'], interest_tags: ['self-care', 'relaxing', 'wellness'], time_needed: '1 hour', cost_level: 'free', location_type: 'indoor', tags: ['self-care', 'relaxing', 'wellness', 'free'] },

  // FOOD
  { title: 'The Best Grilled Cheese You Have Ever Made', category: 'food', description: 'Elevate the classic: use good sourdough, two types of cheese (one melty like gruyere, one sharp like aged cheddar), butter the bread generously, and cook low and slow. Add a thin layer of jam or tomato soup for dipping.', why_good: 'Takes 15 minutes, costs a few dollars, and is genuinely one of the most satisfying foods on earth.', best_for: 'Solo lunch, comfort food craving, rainy day', mood_tags: ['cozy', 'tired', 'bored'], interest_tags: ['cooking', 'comfort-food', 'quick'], time_needed: '15-20 min', cost_level: 'low', location_type: 'indoor', tags: ['cooking', 'comfort-food', 'quick', 'cheap'] },
  { title: 'Thai Green Curry from Scratch', category: 'food', description: 'Make an authentic-tasting Thai green curry using store-bought paste, coconut milk, whatever vegetables you have, and protein of choice. Serve over jasmine rice.', why_good: 'Restaurant-quality meal at home for a fraction of the cost. Impressive if you are cooking for someone.', best_for: 'Dinner for two, cooking for friends, weekend project', mood_tags: ['creative', 'social', 'cozy'], interest_tags: ['cooking', 'thai', 'dinner'], time_needed: '45 min', cost_level: 'medium', location_type: 'indoor', tags: ['cooking', 'thai', 'dinner', 'impressive'] },
  { title: 'The Perfect Breakfast Burrito', category: 'food', description: 'Scrambled eggs, crispy hash browns, cheese, avocado, and hot sauce in a warm tortilla. Make a batch of 4 and freeze the rest for future you.', why_good: 'Filling, customizable, and the frozen ones reheat perfectly for busy mornings.', best_for: 'Weekend breakfast, meal prep Sunday', mood_tags: ['cozy', 'hungry', 'relaxed'], interest_tags: ['cooking', 'breakfast', 'meal-prep'], time_needed: '30 min', cost_level: 'low', location_type: 'indoor', tags: ['cooking', 'breakfast', 'meal-prep'] },
  { title: 'Homemade Ramen Bowl', category: 'food', description: 'Start with good instant ramen, then upgrade it: soft-boiled egg, green onions, nori, corn, sesame oil, and chili crisp. The difference is night and day.', why_good: 'Takes instant ramen from sad to spectacular in 10 extra minutes.', best_for: 'Solo dinner, late night craving, cozy evening', mood_tags: ['cozy', 'tired', 'bored'], interest_tags: ['cooking', 'japanese', 'comfort-food'], time_needed: '20 min', cost_level: 'low', location_type: 'indoor', tags: ['cooking', 'japanese', 'comfort-food', 'quick'] },
  { title: 'Build-Your-Own Pizza Night', category: 'food', description: 'Get pre-made dough or naan bread, set out toppings (cheese, veggies, meats, sauces), and let everyone build their own personal pizza.', why_good: 'Interactive, fun, and everyone gets exactly what they want. Great for groups.', best_for: 'Group activity, date night, family dinner', mood_tags: ['social', 'creative', 'fun'], interest_tags: ['cooking', 'pizza', 'social'], time_needed: '45 min', cost_level: 'medium', location_type: 'indoor', tags: ['cooking', 'pizza', 'social', 'group'] },

  // MOVIES
  { title: 'The Grand Budapest Hotel', category: 'movies', description: 'Wes Anderson visually stunning comedy about a legendary concierge and his protege. Whimsical, fast-paced, and endlessly rewatchable.', why_good: 'Perfect when you want something beautiful, funny, and light but smart. The color palette alone is worth watching.', best_for: 'Solo or date night, cozy evening, when you want something artistic but fun', mood_tags: ['cozy', 'creative', 'bored'], interest_tags: ['comedy', 'visual', 'wes-anderson', 'artistic'], time_needed: '1h 40m', cost_level: 'low', location_type: 'online', tags: ['comedy', 'visual', 'artistic', 'cozy'] },
  { title: 'Everything Everywhere All at Once', category: 'movies', description: 'A laundromat owner gets swept into a multiverse adventure. Absurd, emotional, and unlike anything you have seen before.', why_good: 'When you want to feel everything at once. Funny, moving, and wildly creative.', best_for: 'When you want to be surprised, solo or with friends who like weird stuff', mood_tags: ['adventurous', 'creative', 'energetic'], interest_tags: ['sci-fi', 'comedy', 'emotional', 'unique'], time_needed: '2h 20m', cost_level: 'low', location_type: 'online', tags: ['sci-fi', 'comedy', 'emotional', 'unique'] },
  { title: 'Spirited Away', category: 'movies', description: 'Studio Ghibli masterpiece about a girl who enters a magical spirit world. Animated but deeply meaningful for all ages.', why_good: 'The kind of film that stays with you. Beautiful, strange, and deeply human.', best_for: 'Solo or family, rainy afternoon, when you want to feel wonder', mood_tags: ['cozy', 'creative', 'nostalgic'], interest_tags: ['animation', 'fantasy', 'ghibli', 'family'], time_needed: '2h 5m', cost_level: 'low', location_type: 'online', tags: ['animation', 'fantasy', 'ghibli', 'family'] },
  { title: 'The Social Network', category: 'movies', description: 'The story of Facebooks creation, told with razor-sharp dialogue and a propulsive score. More thriller than tech movie.', why_good: 'Incredibly watchable. The dialogue is addictive and the pacing never lets up.', best_for: 'Solo, focused viewing, when you want something smart and fast', mood_tags: ['focused', 'energetic', 'bored'], interest_tags: ['drama', 'tech', 'dialogue', 'fast-paced'], time_needed: '2h', cost_level: 'low', location_type: 'online', tags: ['drama', 'tech', 'dialogue', 'fast-paced'] },
  { title: 'Knives Out', category: 'movies', description: 'A star-studded murder mystery that is clever, funny, and genuinely surprising. Daniel Craig plays a Southern detective investigating a wealthy familys patriarchs death.', why_good: 'The kind of movie everyone in the room will enjoy. Smart without being stuffy.', best_for: 'Group movie night, date night, when you want something fun and clever', mood_tags: ['social', 'energetic', 'bored'], interest_tags: ['mystery', 'comedy', 'ensemble', 'clever'], time_needed: '2h 10m', cost_level: 'low', location_type: 'online', tags: ['mystery', 'comedy', 'ensemble', 'clever'] },

  // TV SHOWS
  { title: 'Severance (Season 1)', category: 'tv_shows', description: 'Employees at a corporation undergo a procedure that separates their work memories from their personal ones. Unsettling, brilliant, and completely original.', why_good: 'The kind of show that makes you think for days after each episode. Incredible production design and performances.', best_for: 'Solo binge, focused viewing, when you want something genuinely unique', mood_tags: ['focused', 'adventurous', 'bored'], interest_tags: ['sci-fi', 'thriller', 'workplace', 'mind-bending'], time_needed: '8 episodes, ~45 min each', cost_level: 'medium', location_type: 'online', tags: ['sci-fi', 'thriller', 'mind-bending', 'binge'] },
  { title: 'The Bear (Season 1)', category: 'tv_shows', description: 'A fine-dining chef returns to Chicago to run his familys sandwich shop. Intense, emotional, and surprisingly funny.', why_good: 'Short episodes, incredible acting, and the kitchen scenes are genuinely stressful in the best way.', best_for: 'Solo or with a partner, when you want something short and powerful', mood_tags: ['energetic', 'focused', 'creative'], interest_tags: ['drama', 'food', 'intense', 'short-episodes'], time_needed: '8 episodes, ~30 min each', cost_level: 'medium', location_type: 'online', tags: ['drama', 'food', 'intense', 'short-episodes'] },
  { title: 'Bluey', category: 'tv_shows', description: 'An Australian animated show about a family of dogs. Made for kids but genuinely one of the best shows on television for any age.', why_good: '7-minute episodes that are funny, heartwarming, and surprisingly deep. Perfect for when you need a mood boost.', best_for: 'Solo, with kids, study break, when you need something wholesome', mood_tags: ['relaxed', 'cozy', 'nostalgic'], interest_tags: ['animation', 'family', 'wholesome', 'short'], time_needed: '7 min per episode', cost_level: 'low', location_type: 'online', tags: ['animation', 'family', 'wholesome', 'short'] },
  { title: 'Arcane', category: 'tv_shows', description: 'Animated series set in the League of Legends universe. Stunning animation, complex characters, and a story that works even if you know nothing about the game.', why_good: 'The animation is unlike anything else on television. The story is genuinely gripping.', best_for: 'Solo or with friends who appreciate great animation', mood_tags: ['adventurous', 'energetic', 'focused'], interest_tags: ['animation', 'fantasy', 'action', 'stunning-visuals'], time_needed: '9 episodes, ~45 min each', cost_level: 'low', location_type: 'online', tags: ['animation', 'fantasy', 'action', 'stunning-visuals'] },
  { title: 'Shogun (2024)', category: 'tv_shows', description: 'A English navigator becomes embroiled in Japanese political intrigue. Gorgeous, epic, and completely absorbing.', why_good: 'Feels like a 10-hour movie. The production value is insane and the story is genuinely gripping from episode one.', best_for: 'Solo or with a partner, weekend binge, when you want to be transported', mood_tags: ['adventurous', 'focused', 'energetic'], interest_tags: ['historical', 'drama', 'epic', 'japanese'], time_needed: '10 episodes, ~1 hour each', cost_level: 'medium', location_type: 'online', tags: ['historical', 'drama', 'epic', 'japanese'] },

  // BOOKS
  { title: 'Project Hail Mary by Andy Weir', category: 'books', description: 'A lone astronaut must save Earth with the help of an unexpected ally. From the author of The Martian. Funny, smart, and deeply satisfying.', why_good: 'The kind of book you cannot put down. Science-heavy but accessible, with a friendship at its core that will make you emotional.', best_for: 'Solo reading, when you want a page-turner that is also smart', mood_tags: ['adventurous', 'focused', 'bored'], interest_tags: ['sci-fi', 'humor', 'friendship', 'page-turner'], time_needed: '12-15 hours', cost_level: 'low', location_type: 'any', tags: ['sci-fi', 'humor', 'friendship', 'page-turner'] },
  { title: 'Atomic Habits by James Clear', category: 'books', description: 'A practical guide to building good habits and breaking bad ones. Based on real science, not motivation.', why_good: 'Actually useful. You will start applying the ideas immediately. Short chapters make it easy to read in small chunks.', best_for: 'Solo reading, morning routine, when you want to improve yourself', mood_tags: ['focused', 'relaxed', 'creative'], interest_tags: ['self-improvement', 'productivity', 'psychology', 'practical'], time_needed: '8-10 hours', cost_level: 'low', location_type: 'any', tags: ['self-improvement', 'productivity', 'psychology', 'practical'] },
  { title: 'The House in the Cerulean Sea by TJ Klune', category: 'books', description: 'A caseworker visits a magical orphanage and finds a found family. Warm, funny, and deeply comforting.', why_good: 'Like a warm hug in book form. Perfect when you need something kind and hopeful.', best_for: 'Solo reading, cozy evening, when you need comfort', mood_tags: ['cozy', 'relaxed', 'nostalgic'], interest_tags: ['fantasy', 'found-family', 'cozy', 'lgbtq'], time_needed: '8-10 hours', cost_level: 'low', location_type: 'any', tags: ['fantasy', 'found-family', 'cozy', 'lgbtq'] },
  { title: 'Tomorrow, and Tomorrow, and Tomorrow by Gabrielle Zevin', category: 'books', description: 'Two friends build a video game empire over decades. A story about creativity, partnership, and the games we play.', why_good: 'Even if you do not care about video games, this book is about so much more. Beautiful writing and deeply human characters.', best_for: 'Solo reading, when you want something literary but accessible', mood_tags: ['creative', 'nostalgic', 'focused'], interest_tags: ['literary-fiction', 'friendship', 'games', 'creativity'], time_needed: '12-15 hours', cost_level: 'low', location_type: 'any', tags: ['literary-fiction', 'friendship', 'games', 'creativity'] },
  { title: 'Piranesi by Susanna Clarke', category: 'books', description: 'A man lives in an infinite house filled with statues and tides. Mysterious, beautiful, and unlike anything else.', why_good: 'Short, immersive, and will make you see the world differently. The kind of book that stays with you.', best_for: 'Solo reading, when you want something strange and beautiful', mood_tags: ['creative', 'adventurous', 'relaxed'], interest_tags: ['fantasy', 'mystery', 'literary', 'unique'], time_needed: '6-8 hours', cost_level: 'low', location_type: 'any', tags: ['fantasy', 'mystery', 'literary', 'unique'] },

  // MUSIC
  { title: 'Current Joys — A Full Album Listen', category: 'music', description: 'Put on Current Joy album Wild Heart and listen start to finish. Lo-fi, dreamy, perfect for a late-night walk or just lying on the floor thinking about life.', why_good: 'The kind of album that makes ordinary moments feel cinematic. Great headphones album.', best_for: 'Solo, late night, when you want to feel something', mood_tags: ['relaxed', 'nostalgic', 'cozy'], interest_tags: ['lo-fi', 'dreamy', 'indie', 'ambient'], time_needed: '45 min', cost_level: 'free', location_type: 'online', tags: ['lo-fi', 'dreamy', 'indie', 'ambient'] },
  { title: 'Khruangbin — Con Todo El Mundo', category: 'music', description: 'Texas trio blending Thai funk, surf rock, and global grooves. Instrumental, warm, and impossibly smooth.', why_good: 'Perfect background music that is also interesting enough to actively listen to. Makes everything feel like a movie.', best_for: 'Cooking, hanging with friends, driving, studying', mood_tags: ['relaxed', 'social', 'cozy'], interest_tags: ['instrumental', 'funk', 'world-music', 'chill'], time_needed: '40 min', cost_level: 'free', location_type: 'online', tags: ['instrumental', 'funk', 'world-music', 'chill'] },
  { title: 'SZA — SOS', category: 'music', description: '23 tracks of raw, honest R&B that goes from heartbreak to empowerment. Incredibly well-produced and deeply relatable.', why_good: 'The kind of album you can live in for weeks. Every track is strong.', best_for: 'Solo, getting ready, driving, when you want to feel seen', mood_tags: ['energetic', 'nostalgic', 'social'], interest_tags: ['rnb', 'pop', 'emotional', 'empowering'], time_needed: '1h 10m', cost_level: 'free', location_type: 'online', tags: ['rnb', 'pop', 'emotional', 'empowering'] },
  { title: 'Nujabes — Metaphorical Music', category: 'music', description: 'Japanese producer blending jazz and hip-hop into something timeless. The ultimate study/chill album.', why_good: 'Warm, jazzy beats that make you feel like you are in an anime about your own life.', best_for: 'Studying, working, relaxing, rainy days', mood_tags: ['focused', 'relaxed', 'cozy'], interest_tags: ['jazz', 'hip-hop', 'instrumental', 'chill'], time_needed: '50 min', cost_level: 'free', location_type: 'online', tags: ['jazz', 'hip-hop', 'instrumental', 'chill'] },
  { title: 'Faye Webster — I Know I am Funny haha', category: 'music', description: 'Dreamy indie folk with deadpan lyrics about love and Atlanta. Quietly brilliant.', why_good: 'The kind of music that feels like a warm afternoon. Subtle but deeply affecting.', best_for: 'Solo, afternoon, when you want something gentle', mood_tags: ['relaxed', 'nostalgic', 'cozy'], interest_tags: ['indie', 'folk', 'dreamy', 'gentle'], time_needed: '35 min', cost_level: 'free', location_type: 'online', tags: ['indie', 'folk', 'dreamy', 'gentle'] },

  // PODCASTS
  { title: 'Huberman Lab — Episode on Sleep', category: 'podcasts', description: 'Dr. Andrew Huberman breaks down the science of sleep and gives actionable tools to improve it. Non-negotiable listening.', why_good: 'You will actually sleep better after this. The tools are simple and immediately applicable.', best_for: 'Solo, evening, when you want to improve your life', mood_tags: ['focused', 'relaxed', 'tired'], interest_tags: ['science', 'health', 'sleep', 'self-improvement'], time_needed: '2 hours', cost_level: 'free', location_type: 'online', tags: ['science', 'health', 'sleep', 'self-improvement'] },
  { title: 'Heavyweight by Jonathan Goldstein', category: 'podcasts', description: 'Jonathan helps people resolve unresolved moments from their past. Funny, moving, and deeply human.', why_good: 'The kind of podcast that makes you laugh and cry in the same episode. Incredibly well-crafted storytelling.', best_for: 'Solo, walking, commuting, when you want to feel something', mood_tags: ['nostalgic', 'relaxed', 'social'], interest_tags: ['storytelling', 'emotional', 'funny', 'human'], time_needed: '30-60 min per episode', cost_level: 'free', location_type: 'online', tags: ['storytelling', 'emotional', 'funny', 'human'] },
  { title: 'Ologies with Alie Ward', category: 'podcasts', description: 'Alie Ward interviews scientists about their fields. Fun, fascinating, and you will learn something incredible every episode.', why_good: 'Makes science genuinely entertaining. Pick any topic that sounds interesting — you will not be disappointed.', best_for: 'Solo, walking, cooking, when you want to learn something cool', mood_tags: ['adventurous', 'focused', 'creative'], interest_tags: ['science', 'learning', 'fun', 'interview'], time_needed: '1 hour per episode', cost_level: 'free', location_type: 'online', tags: ['science', 'learning', 'fun', 'interview'] },
  { title: 'The Daily — Any Recent Episode', category: 'podcasts', description: 'NYT daily news podcast. 20-30 minutes that will make you the most informed person in the room.', why_good: 'Efficient, well-produced, and covers what actually matters. Perfect morning listening.', best_for: 'Morning routine, commute, when you want to stay informed', mood_tags: ['focused', 'energetic'], interest_tags: ['news', 'current-events', 'informative', 'daily'], time_needed: '20-30 min', cost_level: 'free', location_type: 'online', tags: ['news', 'current-events', 'informative', 'daily'] },
  { title: 'SmartLess with Jason Bateman', category: 'podcasts', description: 'Three friends interview celebrities. The chemistry is genuine and the conversations go to unexpected places.', why_good: 'Feels like eavesdropping on a great conversation between funny people. Consistently entertaining.', best_for: 'Solo, driving, working out, when you want to be entertained', mood_tags: ['social', 'energetic', 'bored'], interest_tags: ['comedy', 'interview', 'celebrity', 'conversational'], time_needed: '1 hour per episode', cost_level: 'free', location_type: 'online', tags: ['comedy', 'interview', 'celebrity', 'conversational'] },

  // GAMES
  { title: 'Stardew Valley', category: 'games', description: 'Farm simulation where you inherit a plot of land and build a life. Farming, fishing, mining, relationships, and community.', why_good: 'The ultimate comfort game. No pressure, endless content, and genuinely relaxing. You will lose 100 hours.', best_for: 'Solo, cozy evenings, when you want to zone out productively', mood_tags: ['relaxed', 'cozy', 'bored'], interest_tags: ['simulation', 'farming', 'cozy', 'endless'], time_needed: 'Infinite', cost_level: 'medium', location_type: 'any', tags: ['simulation', 'farming', 'cozy', 'endless'] },
  { title: 'It Takes Two', category: 'games', description: 'Co-op adventure where two players work together to save a relationship. Creative, funny, and constantly surprising.', why_good: 'One of the best co-op games ever made. Every level introduces something new. Perfect for playing with a partner or friend.', best_for: 'With a friend or partner, weekend gaming session', mood_tags: ['social', 'adventurous', 'energetic'], interest_tags: ['co-op', 'adventure', 'creative', 'story'], time_needed: '12-15 hours', cost_level: 'medium', location_type: 'any', tags: ['co-op', 'adventure', 'creative', 'story'] },
  { title: 'Celeste', category: 'games', description: 'Precision platformer about climbing a mountain. Tight controls, beautiful pixel art, and a genuinely moving story about anxiety and perseverance.', why_good: 'Challenging but fair. The story hits hard. One of the best indie games of the decade.', best_for: 'Solo, focused gaming session, when you want a challenge', mood_tags: ['focused', 'adventurous', 'energetic'], interest_tags: ['platformer', 'indie', 'challenging', 'story'], time_needed: '8-10 hours', cost_level: 'low', location_type: 'any', tags: ['platformer', 'indie', 'challenging', 'story'] },
  { title: 'Jackbox Party Pack', category: 'games', description: 'Collection of party games where players use their phones as controllers. Trivia, drawing, word games, and more.', why_good: 'The best party game that exists. Anyone can play, no gaming experience needed, and it is hilarious every time.', best_for: 'Group activity, parties, game night with friends', mood_tags: ['social', 'energetic', 'fun'], interest_tags: ['party', 'multiplayer', 'trivia', 'funny'], time_needed: '1-3 hours', cost_level: 'medium', location_type: 'any', tags: ['party', 'multiplayer', 'trivia', 'funny'] },
  { title: 'Wordle + Connections + Strands Combo', category: 'games', description: 'Do all three NYT games in sequence. Wordle for word skills, Connections for pattern recognition, Strands for word search with a twist.', why_good: 'Takes 15 minutes, exercises your brain, and gives you a small sense of accomplishment to start the day.', best_for: 'Morning routine, solo, coffee break', mood_tags: ['focused', 'relaxed', 'bored'], interest_tags: ['puzzle', 'words', 'daily', 'quick'], time_needed: '15 min', cost_level: 'free', location_type: 'online', tags: ['puzzle', 'words', 'daily', 'quick'] },

  // PLACES
  { title: 'Your Local Independent Bookstore', category: 'places', description: 'Go to a local bookstore you have never been to. Wander without a goal. Pick up books that catch your eye. Maybe buy one.', why_good: 'Bookstores are magic. You will always find something unexpected, and supporting local businesses feels good.', best_for: 'Solo or with a friend, weekend afternoon, when you want to browse', mood_tags: ['relaxed', 'creative', 'bored'], interest_tags: ['books', 'local', 'browsing', 'cozy'], time_needed: '1-2 hours', cost_level: 'low', location_type: 'local', tags: ['books', 'local', 'browsing', 'cozy'] },
  { title: 'A Farmers Market You Have Never Visited', category: 'places', description: 'Find a farmers market in your area you have never been to. Try samples, buy something unusual, and talk to vendors.', why_good: 'Fresh air, fresh food, and a sense of community. You will discover new foods and support local farmers.', best_for: 'Solo or with family, weekend morning, nice weather', mood_tags: ['social', 'adventurous', 'relaxed'], interest_tags: ['food', 'local', 'outdoor', 'community'], time_needed: '1-2 hours', cost_level: 'low', location_type: 'local', tags: ['food', 'local', 'outdoor', 'community'] },
  { title: 'A Museum on a Free Day', category: 'places', description: 'Find a museum near you with a free admission day. Go without a plan and let yourself be surprised.', why_good: 'Culture for free. You will see something that changes your perspective, even if it is small.', best_for: 'Solo or with a friend, rainy day, when you want to learn', mood_tags: ['focused', 'creative', 'relaxed'], interest_tags: ['art', 'culture', 'learning', 'free'], time_needed: '2-3 hours', cost_level: 'free', location_type: 'local', tags: ['art', 'culture', 'learning', 'free'] },
  { title: 'A Park You Have Never Been To', category: 'places', description: 'Find the nearest park you have never visited. Bring a book, a snack, or nothing. Just exist there for a while.', why_good: 'Free, peaceful, and good for your mental health. Sometimes the best plan is no plan.', best_for: 'Solo, nice weather, when you need to decompress', mood_tags: ['relaxed', 'tired', 'bored'], interest_tags: ['nature', 'peaceful', 'free', 'outdoor'], time_needed: '30 min - 2 hours', cost_level: 'free', location_type: 'outdoor', tags: ['nature', 'peaceful', 'free', 'outdoor'] },
  { title: 'A Coffee Shop You Have Never Tried', category: 'places', description: 'Pick a coffee shop you have never been to. Order something you have never tried. Sit and people-watch or read.', why_good: 'A small adventure that costs $5. New environment, new vibes, and good coffee.', best_for: 'Solo, working remotely, when you need a change of scenery', mood_tags: ['focused', 'relaxed', 'creative'], interest_tags: ['coffee', 'working', 'people-watching', 'cozy'], time_needed: '1-2 hours', cost_level: 'low', location_type: 'local', tags: ['coffee', 'working', 'people-watching', 'cozy'] },

  // DATE IDEAS
  { title: 'Sunset Picnic with Store-Bought Everything', category: 'date_ideas', description: 'Go to a grocery store, buy cheese, bread, fruit, and a drink. Drive or walk to a scenic spot. Watch the sunset together.', why_good: 'Romantic without being expensive or complicated. The effort matters more than the cost.', best_for: 'Date night, new relationship or long-term, clear evening', mood_tags: ['romantic', 'relaxed', 'cozy'], interest_tags: ['picnic', 'sunset', 'food', 'romantic'], time_needed: '2 hours', cost_level: 'low', location_type: 'outdoor', tags: ['picnic', 'sunset', 'food', 'romantic'] },
  { title: 'Cook a Meal Together from Scratch', category: 'date_ideas', description: 'Pick a recipe neither of you has made before. Shop for ingredients together, cook together, and eat by candlelight.', why_good: 'Collaborative, intimate, and you get to eat the results. The process is the date.', best_for: 'Date night, couples who like cooking, weekend evening', mood_tags: ['romantic', 'creative', 'social'], interest_tags: ['cooking', 'collaborative', 'food', 'intimate'], time_needed: '2-3 hours', cost_level: 'medium', location_type: 'indoor', tags: ['cooking', 'collaborative', 'food', 'intimate'] },
  { title: 'Thrift Store Challenge', category: 'date_ideas', description: 'Each person gets $10 and 30 minutes to find the most interesting, funny, or thoughtful gift for the other person.', why_good: 'Reveals personality, creates inside jokes, and is genuinely fun. The gifts become meaningful.', best_for: 'Date night, playful couples, weekend afternoon', mood_tags: ['social', 'creative', 'fun'], interest_tags: ['shopping', 'playful', 'gifts', 'budget'], time_needed: '1-2 hours', cost_level: 'low', location_type: 'local', tags: ['shopping', 'playful', 'gifts', 'budget'] },
  { title: 'Stargazing with Hot Drinks', category: 'date_ideas', description: 'Drive somewhere with less light pollution. Bring blankets, hot chocolate or tea, and just look up. Use a stargazing app to identify constellations.', why_good: 'Free, romantic, and genuinely awe-inspiring. The kind of date you remember for years.', best_for: 'Date night, clear night, when you want something memorable', mood_tags: ['romantic', 'relaxed', 'adventurous'], interest_tags: ['stargazing', 'nature', 'romantic', 'free'], time_needed: '1-2 hours', cost_level: 'free', location_type: 'outdoor', tags: ['stargazing', 'nature', 'romantic', 'free'] },

  // GROUP IDEAS
  { title: 'Board Game Cafe Night', category: 'group_ideas', description: 'Find a board game cafe near you. Order drinks, pick a game none of you have played, and spend the evening competing and laughing.', why_good: 'Social, interactive, and you do not have to be good at anything. The games do the work.', best_for: 'Group of 3-6, weekend evening, when you want to be social', mood_tags: ['social', 'energetic', 'fun'], interest_tags: ['board-games', 'social', 'competitive', 'indoor'], time_needed: '2-3 hours', cost_level: 'low', location_type: 'local', tags: ['board-games', 'social', 'competitive', 'indoor'] },
  { title: 'Potluck Dinner Party', category: 'group_ideas', description: 'Everyone brings a dish. Set a theme (comfort food, childhood favorites, one color) to make it more interesting.', why_good: 'Everyone contributes, variety of food, and the theme makes it memorable. Low cost per person.', best_for: 'Group of 4-8, weekend evening, food lovers', mood_tags: ['social', 'cozy', 'creative'], interest_tags: ['food', 'potluck', 'social', 'themed'], time_needed: '2-3 hours', cost_level: 'low', location_type: 'indoor', tags: ['food', 'potluck', 'social', 'themed'] },
  { title: 'Outdoor Movie Night', category: 'group_ideas', description: 'Hang a white sheet, set up a projector (or use a TV outdoors), make popcorn, and watch a movie under the stars.', why_good: 'Feels special without being expensive. The outdoor setting makes any movie feel like an event.', best_for: 'Group of 3-8, clear evening, backyard or park', mood_tags: ['social', 'cozy', 'relaxed'], interest_tags: ['movies', 'outdoor', 'social', 'summer'], time_needed: '3-4 hours', cost_level: 'low', location_type: 'outdoor', tags: ['movies', 'outdoor', 'social', 'summer'] },
  { title: 'Group Hike with a Picnic at the Top', category: 'group_ideas', description: 'Pick a hike with a good viewpoint. Everyone brings one item for a shared picnic. Eat at the summit.', why_good: 'Exercise, nature, and food. The shared goal makes it bonding, and the view is the reward.', best_for: 'Group of 3-6, nice weather, active friends', mood_tags: ['adventurous', 'social', 'energetic'], interest_tags: ['hiking', 'nature', 'picnic', 'outdoor'], time_needed: '3-5 hours', cost_level: 'free', location_type: 'outdoor', tags: ['hiking', 'nature', 'picnic', 'outdoor'] },

  // SOLO IDEAS
  { title: 'Morning Pages Journaling', category: 'solo_ideas', description: 'Write 3 pages of stream-of-consciousness writing first thing in the morning. No editing, no judgment. Just dump your thoughts onto paper.', why_good: 'Clears your mind, improves creativity, and helps you understand yourself better. Free and takes 20 minutes.', best_for: 'Solo, morning routine, when you feel stuck or overwhelmed', mood_tags: ['focused', 'creative', 'relaxed'], interest_tags: ['writing', 'journaling', 'self-improvement', 'morning'], time_needed: '20-30 min', cost_level: 'free', location_type: 'any', tags: ['writing', 'journaling', 'self-improvement', 'morning'] },
  { title: 'Learn to Juggle', category: 'solo_ideas', description: 'Get three balls (or rolled-up socks) and YouTube a juggling tutorial. Practice for 30 minutes. You will be terrible and it will be great.', why_good: 'Improves coordination, is genuinely fun to learn, and gives you a party trick. Free and meditative.', best_for: 'Solo, bored, when you want to learn something physical', mood_tags: ['bored', 'creative', 'energetic'], interest_tags: ['skills', 'coordination', 'fun', 'free'], time_needed: '30 min', cost_level: 'free', location_type: 'any', tags: ['skills', 'coordination', 'fun', 'free'] },
  { title: 'Digital Declutter Session', category: 'solo_ideas', description: 'Spend an hour organizing your phone: delete unused apps, organize photos, clear downloads, unsubscribe from emails. Your phone will feel new.', why_good: 'Takes one hour and makes your daily tech experience noticeably better. Surprisingly satisfying.', best_for: 'Solo, weekend, when you want to feel productive', mood_tags: ['focused', 'relaxed', 'bored'], interest_tags: ['productivity', 'organization', 'digital', 'free'], time_needed: '1 hour', cost_level: 'free', location_type: 'any', tags: ['productivity', 'organization', 'digital', 'free'] },
  { title: 'Solo Coffee Shop Reading Session', category: 'solo_ideas', description: 'Bring a book to a coffee shop. Order one drink. Read for 2 hours without checking your phone.', why_good: 'Feels luxurious and productive. The change of environment makes reading more enjoyable.', best_for: 'Solo, weekend, when you want to feel like a main character', mood_tags: ['relaxed', 'cozy', 'focused'], interest_tags: ['reading', 'coffee', 'solo', 'cozy'], time_needed: '2 hours', cost_level: 'low', location_type: 'local', tags: ['reading', 'coffee', 'solo', 'cozy'] },

  // FREE IDEAS
  { title: 'Library Card Adventure', category: 'free_ideas', description: 'Go to your local library. Get a card if you do not have one. Borrow 3 things: a book, a movie, and something you have never tried (magazine, audiobook, puzzle).', why_good: 'Everything is free. Libraries are underrated treasure troves. You might discover a new favorite.', best_for: 'Solo or with kids, any day, when you want free entertainment', mood_tags: ['relaxed', 'curious', 'bored'], interest_tags: ['library', 'free', 'books', 'discovery'], time_needed: '1-2 hours', cost_level: 'free', location_type: 'local', tags: ['library', 'free', 'books', 'discovery'] },
  { title: 'YouTube University', category: 'free_ideas', description: 'Pick a skill you have always wanted to learn. Find the best YouTube tutorial series. Watch the first 3 videos and practice for 30 minutes.', why_good: 'Free education from world-class teachers. The hardest part is choosing what to learn.', best_for: 'Solo, when you want to learn something new', mood_tags: ['focused', 'creative', 'bored'], interest_tags: ['learning', 'youtube', 'skills', 'free'], time_needed: '1-2 hours', cost_level: 'free', location_type: 'online', tags: ['learning', 'youtube', 'skills', 'free'] },
  { title: 'People Watching at a Busy Cafe', category: 'free_ideas', description: 'Sit at a busy cafe or park with a drink. Watch people. Make up stories about their lives. It is free entertainment that exercises your creativity.', why_good: 'Free, relaxing, and surprisingly engaging. Great for writers or anyone who likes observing human behavior.', best_for: 'Solo, any time, when you want to people-watch', mood_tags: ['relaxed', 'creative', 'bored'], interest_tags: ['people-watching', 'creative', 'free', 'observing'], time_needed: '30 min - 1 hour', cost_level: 'free', location_type: 'any', tags: ['people-watching', 'creative', 'free', 'observing'] },
  { title: 'Free Museum or Gallery Day', category: 'free_ideas', description: 'Research free museum days in your area. Go without a plan. Spend 2 hours wandering and looking at things that catch your eye.', why_good: 'Culture, exercise, and inspiration — all free. You will see something that changes your perspective.', best_for: 'Solo or with a friend, weekend, when you want to feel cultured', mood_tags: ['relaxed', 'creative', 'focused'], interest_tags: ['art', 'culture', 'free', 'walking'], time_needed: '2-3 hours', cost_level: 'free', location_type: 'local', tags: ['art', 'culture', 'free', 'walking'] },

  // LOW BUDGET
  { title: 'Dollar Store Craft Challenge', category: 'low_budget', description: 'Go to a dollar store with $5. Buy random supplies. Make something — a decoration, a gift, an art project. The constraint breeds creativity.', why_good: 'Forces creativity through limitation. You will be surprised what you can make with $5 of random supplies.', best_for: 'Solo or with friends, weekend, when you want to make something', mood_tags: ['creative', 'bored', 'fun'], interest_tags: ['crafts', 'budget', 'creative', 'diy'], time_needed: '1-2 hours', cost_level: 'low', location_type: 'any', tags: ['crafts', 'budget', 'creative', 'diy'] },
  { title: 'Make a Time Capsule', category: 'low_budget', description: 'Write a letter to your future self. Add a photo, a small object, a list of current favorites. Seal it and set a date to open it.', why_good: 'Costs nothing, takes 30 minutes, and future you will be grateful. A meaningful ritual.', best_for: 'Solo, reflective mood, when you want to do something meaningful', mood_tags: ['nostalgic', 'creative', 'relaxed'], interest_tags: ['writing', 'reflection', 'free', 'meaningful'], time_needed: '30 min', cost_level: 'free', location_type: 'any', tags: ['writing', 'reflection', 'free', 'meaningful'] },
  { title: 'Create a Personal Playlist for Your Current Mood', category: 'low_budget', description: 'Spend an hour building a playlist that perfectly captures how you feel right now. Give it a name. Add songs that match the vibe.', why_good: 'Free, creative, and you end up with a playlist you will actually use. Great for processing emotions.', best_for: 'Solo, any time, when you want to feel something', mood_tags: ['creative', 'nostalgic', 'relaxed'], interest_tags: ['music', 'playlist', 'creative', 'free'], time_needed: '1 hour', cost_level: 'free', location_type: 'online', tags: ['music', 'playlist', 'creative', 'free'] },
  { title: 'Go on a Photo Walk with Your Phone', category: 'low_budget', description: 'Walk around your neighborhood with the sole purpose of taking interesting photos. Look for patterns, colors, textures, and unexpected moments.', why_good: 'Free exercise that trains your eye. You will start seeing your surroundings differently.', best_for: 'Solo, nice weather, when you want to be creative', mood_tags: ['creative', 'relaxed', 'adventurous'], interest_tags: ['photography', 'walking', 'creative', 'free'], time_needed: '1-2 hours', cost_level: 'free', location_type: 'outdoor', tags: ['photography', 'walking', 'creative', 'free'] },

  // WEEKEND IDEAS
  { title: 'Farmers Market + Cooking Day', category: 'weekend_ideas', description: 'Go to a farmers market in the morning. Buy seasonal ingredients. Spend the afternoon cooking a meal from scratch with what you found.', why_good: 'Supports local farmers, gets you outside, and ends with an incredible meal. The full experience.', best_for: 'Solo or with a partner, Saturday morning through afternoon', mood_tags: ['creative', 'social', 'relaxed'], interest_tags: ['food', 'cooking', 'market', 'weekend'], time_needed: '4-5 hours', cost_level: 'medium', location_type: 'local', tags: ['food', 'cooking', 'market', 'weekend'] },
  { title: 'Day Trip to a Nearby Town', category: 'weekend_ideas', description: 'Pick a town within 1 hour drive that you have never visited. Go without a plan. Walk around, find a cafe, explore.', why_good: 'Feels like a vacation without the cost of travel. New environment, new perspectives.', best_for: 'Solo or with friends, weekend, when you want an adventure', mood_tags: ['adventurous', 'social', 'energetic'], interest_tags: ['travel', 'exploring', 'day-trip', 'new-places'], time_needed: 'Full day', cost_level: 'low', location_type: 'local', tags: ['travel', 'exploring', 'day-trip', 'new-places'] },
  { title: 'Home Movie Marathon with a Theme', category: 'weekend_ideas', description: 'Pick a theme (90s nostalgia, directors best work, comfort movies) and watch 3-4 films back to back with good snacks.', why_good: 'Themed marathons make movie watching feel like an event. Great for solo or with friends.', best_for: 'Solo or group, weekend, when you want to relax', mood_tags: ['cozy', 'relaxed', 'nostalgic'], interest_tags: ['movies', 'marathon', 'themed', 'cozy'], time_needed: '6-8 hours', cost_level: 'free', location_type: 'indoor', tags: ['movies', 'marathon', 'themed', 'cozy'] },
  { title: 'Skill Swap with a Friend', category: 'weekend_ideas', description: 'Each person teaches the other something they are good at. Cooking, a card trick, a language, a sport — anything.', why_good: 'Free, social, and you both learn something new. Strengthens friendships through sharing.', best_for: 'With a friend, weekend, when you want to learn and bond', mood_tags: ['social', 'creative', 'energetic'], interest_tags: ['learning', 'teaching', 'social', 'skills'], time_needed: '2-3 hours', cost_level: 'free', location_type: 'any', tags: ['learning', 'teaching', 'social', 'skills'] },

  // STUDY BREAK
  { title: '10-Minute Dance Break', category: 'study_break', description: 'Put on your favorite upbeat song and dance like nobody is watching. Seriously. Just 3 minutes of movement.', why_good: 'Resets your brain, releases endorphins, and takes exactly one song. Scientifically proven to improve focus.', best_for: 'Solo, study break, when you are stuck', mood_tags: ['energetic', 'bored', 'tired'], interest_tags: ['dance', 'movement', 'quick', 'energy'], time_needed: '3-5 min', cost_level: 'free', location_type: 'any', tags: ['dance', 'movement', 'quick', 'energy'] },
  { title: 'Make a Fancy Snack', category: 'study_break', description: 'Instead of mindless snacking, make something intentional: cut fruit nicely, make a mini charcuterie board, or toast bread with toppings.', why_good: 'Takes 5 minutes, gives you a mental break, and the intentional eating feels like a treat.', best_for: 'Solo, study break, when you need fuel', mood_tags: ['cozy', 'tired', 'bored'], interest_tags: ['food', 'snack', 'quick', 'intentional'], time_needed: '5-10 min', cost_level: 'low', location_type: 'indoor', tags: ['food', 'snack', 'quick', 'intentional'] },
  { title: 'Step Outside for 5 Minutes', category: 'study_break', description: 'Go outside. Look at the sky. Take 10 deep breaths. Feel the air. Come back.', why_good: 'The simplest reset. Fresh air and a change of scenery work wonders for focus.', best_for: 'Solo, any time, when you feel foggy', mood_tags: ['tired', 'relaxed', 'bored'], interest_tags: ['outdoor', 'breathing', 'quick', 'free'], time_needed: '5 min', cost_level: 'free', location_type: 'outdoor', tags: ['outdoor', 'breathing', 'quick', 'free'] },
  { title: 'Doodle or Color for 10 Minutes', category: 'study_break', description: 'Grab a pen and paper. Doodle whatever comes to mind. No skill needed. Just let your hand move.', why_good: 'Engages a different part of your brain. Meditative and surprisingly refreshing.', best_for: 'Solo, study break, when you need to reset', mood_tags: ['relaxed', 'creative', 'bored'], interest_tags: ['drawing', 'creative', 'meditative', 'free'], time_needed: '10 min', cost_level: 'free', location_type: 'any', tags: ['drawing', 'creative', 'meditative', 'free'] },
]
